 http://www.agencebio.org/le-marche-de-la-bio-en-france 
 https://www.larevolutiondestortues.fr/peut-on-faire-confiance-au-bio-de-supermarche/ 
 https://www.latribune.fr/regions/smart-cities/la-ville-face-a-la-perte-du-lien-social-620081.html 
https://academic.oup.com/ije/article/34/4/846/692901
http://www.leparisien.fr/espace-premium/actu/les-jeunes-a-la-ville-et-les-seniors-a-la-campagne-02-07-2015-4911467.php 
 http://www.europe1.fr/france/exclu-les-jeunes-moins-friands-de-jardinage-sondage-1510501 
 https://www.monalisa-asso.fr/actualites/item/l-importance-du-lien-social-pour-etre-heureux-dans-ma-ville 
https://www.insee.fr/fr/statistiques/1892088?sommaire=1912926 
https://www.insee.fr/fr/statistiques/2011101?geo=COM-31555 
https://zoom.earth 
 https://fr.wikipedia.org/wiki/Histoire_de_Toulouse#/media/File:Toulouse_Karte_1631.jpg 
 https://www.colibris-lemouvement.org/
 https://www.definitions-marketing.com/definition/economie-collaborative/ 
 https://www.waterstons.com/articles/keeping-users-happy-the-importance-of-user-experience-ux-in-modern-apps 
 https://fr.wikipedia.org/wiki/Lean_startup  
 https://blog.intercom.com/before-you-send-your-first-message/
 www.plantezcheznous.com
 www.pretersonjardin.com
 www.jepartagemonjardin.fr
 www.allovoisins.com
 www.smiile.com
 http://macadam-gardens.fr
 https://www.facebook.com/events/136050157093231/ 
 https://www.godaddy.com 
 https://medium.com/@bezdelev/cost-breakdown-for-a-static-website-on-aws-after-18-months-in-production-d97a932d2d25 
 